version: '3'
services:
  web:
    build: .
    container_name: bytebot-flask-backend
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    command: sh -c "python app.py"
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    container_name: bytebot-redis
    ports:
      - "6379:6379"

